### PR TITLE
Remove AGNOSTIC-LIZARD

### LINKED ISSUE #110: Agnostic Lizard, a dependency for Serapeum tests, is GPLv3+
https://github.com/ruricolist/serapeum/blob/4692fd467e6f4b48ef8d142936648bb5dc5deccd/serapeum.asd#L115

I screwed up in 390054dc9 and introduced a GPLv3 dependency into Serapeum's tests - it's used only for `macroexpand-all`, so it should be possible to remove it and use e.g. https://github.com/cbaggers/trivial-macroexpand-all instead.

I'm on it now.

### PR DESCRIPTION
**Pull request by phoe**
Fixes #110

### CODE REVIEW

**Comment by phoe** [comment]
https://app.travis-ci.com/github/phoe-trash/serapeum/jobs/557125258

`TEST-WITH-BOOLEAN-EXPANSION` fails on CCL because CCL's macroexpander seems to strip away all `MACROLET` forms from the resulting expansion. (I guess it's allowed to do that, since they are no longer necessary in the expansion.)

What do we do? Does it make sense to remove that test as well and only perform black-box testing of `WITH-BOOLEAN`?

**Comment by ruricolist** [comment]
Note that trivial-macroexpand-all is already a dependency of Serapeum. But I would just drop that test. Depending on the precise details of the full macroexpansion strikes me as brittle anyway.

**Comment by phoe** [comment]
Dropped the test, waiting for CI.

**Comment by phoe** [comment]
CI tells me it's fixed, should be ready for merging.

Apologies for the accidental supply chain attack, I'll be more careful in the future.

**Pull request merged**
